Repository edgexfoundry/edgex-global-pipelines, pull requests merged in 2020-07, with the labels that each got.

#206 (feat)Ability to specify list of API folders for edgex-publish-swagger
  resources/edgex-publish-swagger.sh
  resources/toSwaggerHub.sh
  src/test/groovy/edgeXSwaggerPublishSpec.groovy
  vars/edgeXSwaggerPublish.groovy
Labels: hanoi

#209 add ability to override snap builder image version tag
  vars/edgeXSnap.groovy
Labels: 2-medium, enhancement

#203 Add new environment variables for experimental/stable pattern
  Jenkinsfile
  resources/update-named-tag.sh
  src/test/groovy/edgeXBuildGoAppSpec.groovy
  src/test/groovy/edgeXDockerSpec.groovy
  src/test/groovy/edgeXUpdateNamedTagSpec.groovy
  src/test/groovy/edgexSpec.groovy
  vars/edgeXBuildGoApp.groovy
  vars/edgeXDocker.groovy
  vars/edgeXSemver.groovy
  vars/edgeXUpdateNamedTag.groovy
  vars/edgex.groovy
Labels: enhancement, hanoi

#214 fix: pushAll ignores arm64 image name suffix
  src/test/groovy/edgeXDockerSpec.groovy
  vars/edgeXBuildGoParallel.groovy
  vars/edgeXDocker.groovy
Labels: 3-high, bug

#215 disable Test stage when merging to master
  vars/edgeXBuildGoApp.groovy
  vars/edgeXBuildGoParallel.groovy
Labels: 1-low

#220 fix: add option for git-semver arm64 docker image
  vars/edgeXSemver.groovy
Labels: bug, hanoi

#222 Change swagger path since the path has updated from api/openapi to openapi on edgex-go
  src/test/groovy/edgeXBuildGoAppSpec.groovy
  src/test/groovy/edgeXBuildGoParallelSpec.groovy
  src/test/groovy/edgeXSwaggerPublishSpec.groovy
  vars/edgeXBuildGoApp.groovy
  vars/edgeXBuildGoParallel.groovy
  vars/edgeXSwaggerPublish.groovy
Labels: 2-medium, ci, hanoi

#223 Implement code enhancements to facilitate unit testing
  build.gradle
  src/test/groovy/edgeXBuildCAppSpec.groovy
  src/test/groovy/edgeXBuildDockerSpec.groovy
  src/test/groovy/edgeXBuildGoAppSpec.groovy
  src/test/groovy/edgeXBuildGoModSpec.groovy
  src/test/groovy/edgeXBuildGoParallelSpec.groovy
  src/test/groovy/edgeXClairSpec.groovy
  src/test/groovy/edgeXCodecovSpec.groovy
  src/test/groovy/edgeXDockerLoginSpec.groovy
  src/test/groovy/edgeXDockerSpec.groovy
  src/test/groovy/edgeXGenericSpec.groovy
  src/test/groovy/edgeXInfraLFToolsSignSpec.groovy
  src/test/groovy/edgeXInfraPublishSpec.groovy
  src/test/groovy/edgeXInfraShipLogsSpec.groovy
  src/test/groovy/edgeXNexusPublishSpec.groovy
  src/test/groovy/edgeXReleaseDockerImageIntSpec.groovy
  src/test/groovy/edgeXReleaseDockerImageSpec.groovy
  src/test/groovy/edgeXReleaseGitTagSpec.groovy
  src/test/groovy/edgeXReleaseGitTagUtilSpec.groovy
  src/test/groovy/edgeXReleaseSnapSpec.groovy
  src/test/groovy/edgeXReleaseSpec.groovy
  src/test/groovy/edgeXScmCheckoutSpec.groovy
  src/test/groovy/edgeXSemverSpec.groovy
  src/test/groovy/edgeXSetupEnvironmentSpec.groovy
  src/test/groovy/edgeXSwaggerPublishSpec.groovy
  src/test/groovy/edgeXUpdateNamedTagSpec.groovy
  src/test/groovy/edgexSpec.groovy
  vars/edgeXBuildGoApp.groovy
  vars/edgeXClair.groovy
  vars/edgeXCodecov.groovy
  vars/edgeXDocker.groovy
  vars/edgeXGeneric.groovy
  vars/edgeXInfraLFToolsSign.groovy
  vars/edgeXInfraPublish.groovy
  vars/edgeXInfraShipLogs.groovy
  vars/edgeXNexusPublish.groovy
  vars/edgeXReleaseGitTag.groovy
  vars/edgeXReleaseGitTagUtil.groovy
  vars/edgeXScmCheckout.groovy
  vars/edgeXSemver.groovy
  vars/edgeXSetupEnvironment.groovy
Labels: enhancement, hanoi

#224 feat: Add support for parallel test execution
  Jenkinsfile
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: 1-low, enhancement, hanoi

#225 Remove unnecessary exception wrapping when testing error
  src/test/groovy/edgeXBuildCAppSpec.groovy
  src/test/groovy/edgeXBuildDockerSpec.groovy
  src/test/groovy/edgeXBuildGoAppSpec.groovy
  src/test/groovy/edgeXBuildGoParallelSpec.groovy
  src/test/groovy/edgeXClairSpec.groovy
  src/test/groovy/edgeXDockerLoginSpec.groovy
  src/test/groovy/edgeXGenericSpec.groovy
  src/test/groovy/edgeXInfraLFToolsSignSpec.groovy
  src/test/groovy/edgeXNexusPublishSpec.groovy
  src/test/groovy/edgeXReleaseDockerImageIntSpec.groovy
  src/test/groovy/edgeXReleaseDockerImageSpec.groovy
  src/test/groovy/edgeXReleaseGitTagUtilSpec.groovy
  src/test/groovy/edgeXReleaseSnapSpec.groovy
  src/test/groovy/edgeXSwaggerPublishSpec.groovy
  src/test/groovy/edgeXUpdateNamedTagSpec.groovy
  src/test/groovy/edgexSpec.groovy
  vars/edgeXSetupEnvironment.groovy
Labels: enhancement
