Repository edgexfoundry/edgex-global-pipelines, pull requests merged in 2020-03, with the labels that each got.

#120 pass in ARCH as a build-arg in edgeXDocker.build
  test/edgeXDockerSpec.groovy
  vars/edgeXDocker.groovy
Labels: geneva

#121 Initial commit of the snap global function
  vars/edgeXSnap.groovy
Labels: geneva

#122 add check for copy command if production Jenkins
  vars/edgeXSnap.groovy
Labels: bug, geneva

#119 Update ci-build-image references to refer to the appropriate nexus location
  test/edgeXClairSpec.groovy
  test/edgeXSemverSpec.groovy
  test/edgeXSnykSpec.groovy
  vars/edgeXClair.groovy
  vars/edgeXSemver.groovy
  vars/edgeXSnyk.groovy
Labels: geneva

#114 Add edgeXRelease skeleton functions and first round of unit tests
  test/edgeXReleaseDockerHubSpec.groovy
  test/edgeXReleaseDockerNexusSpec.groovy
  test/edgeXReleaseGitTagSpec.groovy
  test/edgeXReleaseSnapSpec.groovy
  test/edgeXReleaseSpec.groovy
  vars/edgeXRelease.groovy
  vars/edgeXReleaseDockerHub.groovy
  vars/edgeXReleaseDockerNexus.groovy
  vars/edgeXReleaseGitTag.groovy
  vars/edgeXReleaseSnap.groovy
Labels: geneva

#123 update lftools v0.31.0
  test/edgeXInfraLFToolsSignSpec.groovy
  vars/edgeXInfraLFToolsSign.groovy
Labels: geneva

#128 Add releaseBranch parameter to edgexRelease.collectReleaseYamlFiles
  test/edgeXReleaseSpec.groovy
  vars/edgeXRelease.groovy
Labels: bug, geneva

#138 Migrate from Maven to Gradle
  .gitignore
  .idea/codeStyles/codeStyleConfig.xml
  .idea/compiler.xml
  .idea/edgex-global-pipelines.iml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  Jenkinsfile
  build.gradle
  edgex-global-pipelines.iml
  edgex-global-pipelines.ipr
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  pom.xml
  settings.gradle
  src/test/groovy/README.md
  src/test/groovy/edgeXBuildCAppSpec.groovy
  src/test/groovy/edgeXBuildDockerSpec.groovy
  src/test/groovy/edgeXBuildGoAppSpec.groovy
  src/test/groovy/edgeXBuildGoModSpec.groovy
  src/test/groovy/edgeXClairSpec.groovy
  src/test/groovy/edgeXCodecovSpec.groovy
  src/test/groovy/edgeXDockerLoginSpec.groovy
  src/test/groovy/edgeXDockerSpec.groovy
  src/test/groovy/edgeXGenericSpec.groovy
  src/test/groovy/edgeXInfraLFToolsSignSpec.groovy
  src/test/groovy/edgeXInfraPublishSpec.groovy
  src/test/groovy/edgeXInfraShipLogsSpec.groovy
  src/test/groovy/edgeXNexusPublishSpec.groovy
  src/test/groovy/edgeXReleaseDockerHubSpec.groovy
  src/test/groovy/edgeXReleaseDockerNexusSpec.groovy
  src/test/groovy/edgeXReleaseGitTagSpec.groovy
  src/test/groovy/edgeXReleaseSnapSpec.groovy
  src/test/groovy/edgeXReleaseSpec.groovy
  src/test/groovy/edgeXScmCheckoutSpec.groovy
  src/test/groovy/edgeXSemverSpec.groovy
  src/test/groovy/edgeXSetupEnvironmentSpec.groovy
  src/test/groovy/edgeXSnykSpec.groovy
  src/test/groovy/edgexSpec.groovy
  src/test/resources/logback-test.xml
  test/README.md
  test/settings.xml
Labels: 2-medium, enhancement, geneva

#139 update to use new gradle based cache image
  Jenkinsfile
Labels: 1-low, enhancement, geneva

#140 Implement release docker image
  src/test/groovy/edgeXReleaseDockerHubSpec.groovy
  src/test/groovy/edgeXReleaseDockerImageSpec.groovy
  src/test/groovy/edgeXReleaseDockerNexusSpec.groovy
  src/test/groovy/edgeXReleaseSpec.groovy
  vars/edgeXRelease.groovy
  vars/edgeXReleaseDockerHub.groovy
  vars/edgeXReleaseDockerImage.groovy
  vars/edgeXReleaseDockerNexus.groovy
Labels: 2-medium, enhancement, geneva
