Repository edgexfoundry/edgex-global-pipelines, pull requests merged in 2020-01, with the labels that each got.

#78 Pass env variable into edgeXDockerLogin and update edgeXBuildDocker unit tests
  test/README.md
  test/edgeXBuildDockerSpec.groovy
  test/settings.xml
  vars/edgeXBuildDocker.groovy
  vars/edgeXBuildGoApp.groovy
Labels: bug, geneva

#79 move Clair stage back to the main x86_64(amd64) based agent
  vars/edgeXBuildDocker.groovy
  vars/edgeXBuildGoApp.groovy
Labels: bug, geneva

#81 add missing 'node' qualifier
  vars/edgeXBuildGoApp.groovy
Labels: geneva, wip

#82 release stream changes
  vars/edgex.groovy
Labels: enhancement, geneva

#76 Update golang 1.12 version in edgeXBuildGoApp
  test/edgeXBuildGoAppSpec.groovy
  vars/edgeXBuildGoApp.groovy
Labels: geneva

#84 add org name
  vars/edgeXSnyk.groovy
Labels: enhancement, geneva

#88 Add unit test stage to build automation
  Jenkinsfile
Labels: geneva

#89 add beforeAgent to eval when before the agent spins up
  vars/edgeXBuildDocker.groovy
  vars/edgeXBuildGoApp.groovy
  vars/edgeXGeneric.groovy
Labels: enhancement, geneva

#93 enable extra agent call in parallel amd64 stage
  vars/edgeXBuildGoApp.groovy
Labels: bug, geneva

#92 new script to update a named tag
  scripts/update-named-tag.sh
Labels: enhancement, geneva

#94 add GOPROXY support
  test/edgeXBuildGoAppSpec.groovy
  vars/edgeXBuildGoApp.groovy
Labels: enhancement, geneva

#91 Add edgeXBuildCApp function
  test/edgeXBuildCAppSpec.groovy
  vars/edgeXBuildCApp.groovy
Labels: geneva
