Repository edgexfoundry/edgex-global-pipelines, pull requests merged in 2020-06, with the labels that each got.

#186 New functionality to promote and relabel docker images
  src/test/groovy/edgeXBuildGoAppSpec.groovy
  src/test/groovy/edgeXDockerSpec.groovy
  src/test/groovy/edgexSpec.groovy
  vars/edgeXBuildGoApp.groovy
  vars/edgeXDocker.groovy
  vars/edgex.groovy
Labels: 2-medium, f2f-hanoi, hanoi

#198 remove loadGlobalLibrary
  Jenkinsfile
Labels: 1-low, hanoi

#199 use setProperty when setting environment vars
  Jenkinsfile
Labels: 1-low, bug, ci

#197 docs: update pr template to add new dependencies question
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#201 Fix issue with branch name for when conditional
  Jenkinsfile
Labels: 1-low, bug

#204 add new function to build docker images in parallel with docker-compose
  src/test/groovy/edgeXDockerSpec.groovy
  vars/edgeXDocker.groovy
Labels: 2-medium, enhancement, hanoi, phase 1

#205 Global function for SwaggerHub publishing.
  resources/edgex-publish-swagger.sh
  resources/toSwaggerHub.sh
  src/test/groovy/edgeXSwaggerPublishSpec.groovy
  vars/edgeXSwaggerPublish.groovy
Labels: hanoi
