Repository edgexfoundry/edgex-global-pipelines, pull requests merged in 2020-09, with the labels that each got.

#236 feat: update sysstat steps after upstream image change
  src/test/groovy/edgeXInfraShipLogsSpec.groovy
  vars/edgeXInfraShipLogs.groovy
Labels: 2-medium, enhancement, hanoi

#238 feat: add new option for Go 1.15 base image
  src/test/groovy/edgexSpec.groovy
  vars/edgex.groovy
Labels: 2-medium, enhancement, hanoi

#239 feat: update default version of Go to 1.15
  src/test/groovy/edgeXBuildGoAppSpec.groovy
  src/test/groovy/edgeXBuildGoParallelSpec.groovy
  vars/edgeXBuildGoApp.groovy
  vars/edgeXBuildGoParallel.groovy
Labels: 2-medium, enhancement, hanoi

#240 (fix) allow yml as well as yaml extension to be used with edgex-publish-swagger
  resources/edgex-publish-swagger.sh
Labels: bug

#243 refactor: move go version to prep stage
  vars/edgeXBuildGoApp.groovy
  vars/edgeXBuildGoParallel.groovy
Labels: 1-low, hanoi

#245 fix: go version needs to be wrapped within base image
  vars/edgeXBuildGoApp.groovy
  vars/edgeXBuildGoParallel.groovy
Labels: 2-medium, bug, hanoi

#247 feat: add build icon on README
  README.md
Labels: 2-medium, enhancement, hanoi

#244 Add edgeXReleaseGitHubAssets function and update edgeXRelease
  src/test/groovy/edgeXReleaseGitHubAssetsSpec.groovy
  src/test/groovy/edgeXReleaseSpec.groovy
  vars/edgeXRelease.groovy
  vars/edgeXReleaseGitHubAssets.groovy
Labels: enhancement, hanoi

#246 feat: modify edgeXBuildGoApp to include different artifact types
  src/test/groovy/edgeXBuildGoAppSpec.groovy
  vars/edgeXBuildGoApp.groovy
Labels: 2-medium, enhancement, hanoi

#248 fix: edgeXSwaggerPublish - make DRY_RUN default to false unless explicitly defined as 'true'
  src/test/groovy/edgeXSwaggerPublishSpec.groovy
  vars/edgeXSwaggerPublish.groovy
Labels: 1-low

#249 fix: issue with env.ARCH in buildArtifact
  vars/edgeXBuildGoApp.groovy
Labels: 2-medium, bug, enhancement

#250 Add condition for calling edgeXUpdateNamedTag
  Jenkinsfile
  vars/edgeXBuildGoApp.groovy
Labels: bug, hanoi

#228 Switch to lfInfraShipLogs, from LF Pipelines lib
  src/test/groovy/edgeXInfraPublishSpec.groovy
  vars/edgeXInfraPublish.groovy
Labels: 2-medium, ci, enhancement

#251 fix: issue with CodeCov uploader
  src/test/groovy/edgeXCodecovSpec.groovy
  vars/edgeXCodecov.groovy
Labels: 2-medium, bug, hanoi
