Repository edgexfoundry/edgex-global-pipelines, pull requests merged in 2020-04, with the labels that each got.

#143 refactor to use docker image parser
  build.gradle
  src/test/groovy/edgeXDockerSpec.groovy
  src/test/groovy/edgeXReleaseDockerImageSpec.groovy
  vars/edgeXDocker.groovy
  vars/edgeXRelease.groovy
  vars/edgeXReleaseDockerImage.groovy
Labels: 2-medium, enhancement, geneva

#145 remove NonCPS and update inline documentation
  vars/edgeXReleaseDockerImage.groovy
Labels: 2-medium, bug

#146 add docker pull command
  src/test/groovy/edgeXReleaseDockerImageSpec.groovy
  vars/edgeXReleaseDockerImage.groovy
Labels: 2-medium, bug

#148 Implemented EdgeXReleaseGitTag function
  build.gradle
  src/test/groovy/edgeXReleaseGitTagSpec.groovy
  vars/edgeXReleaseGitTag.groovy
Labels: enhancement, geneva

#149 add edgeXDockerLogin
  src/test/groovy/edgeXReleaseDockerImageSpec.groovy
  vars/edgeXReleaseDockerImage.groovy
Labels: 2-medium, enhancement

#150 Update edgeXReleaseGitTag fix sign bug and implement DRY_RUN
  src/test/groovy/edgeXReleaseGitTagSpec.groovy
  vars/edgeXReleaseGitTag.groovy
Labels: bug, enhancement, geneva

#151 fix issue with imageName vs image
  src/test/groovy/edgeXReleaseDockerImageSpec.groovy
  vars/edgeXDocker.groovy
  vars/edgeXReleaseDockerImage.groovy
Labels: bug, geneva

#152 add edgex-global-pipelines release tag information to main pipelines
  Jenkinsfile
  resources/releaseinfo.sh
  src/test/groovy/edgexSpec.groovy
  vars/edgeXBuildCApp.groovy
  vars/edgeXBuildDocker.groovy
  vars/edgeXBuildGoApp.groovy
  vars/edgeXGeneric.groovy
  vars/edgex.groovy
Labels: 2-medium, enhancement, geneva

#154 add bannerMessage before shell script
  src/test/groovy/edgexSpec.groovy
  vars/edgex.groovy
Labels: 1-low, geneva

#155 implement Snap stages for x86 and ARM
  vars/edgeXBuildCApp.groovy
  vars/edgeXBuildGoApp.groovy
Labels: 2-medium, enhancement

#156 Add option for snapChannel and buildSnap
  src/test/groovy/edgeXBuildCAppSpec.groovy
  src/test/groovy/edgeXBuildGoAppSpec.groovy
  vars/edgeXBuildCApp.groovy
  vars/edgeXBuildGoApp.groovy
Labels: 2-medium, enhancement, geneva

#158 Implement EdgeXReleaseSnap function
  src/test/groovy/edgeXReleaseSnapSpec.groovy
  src/test/groovy/edgexSpec.groovy
  vars/edgeXReleaseSnap.groovy
  vars/edgex.groovy
Labels: enhancement, geneva

#161 Update releaseGitTag exception handling add isDryRun reuse
  src/test/groovy/edgeXReleaseGitTagSpec.groovy
  vars/edgeXReleaseGitTag.groovy
Labels: bug, geneva

#163 Update to use explicit snapcraft filename
  src/test/groovy/edgeXReleaseSnapSpec.groovy
  vars/edgeXReleaseSnap.groovy
Labels: enhancement, geneva

#164 refactor yaml to reduce code complexity
  src/test/groovy/edgeXReleaseDockerImageSpec.groovy
  vars/edgeXReleaseDockerImage.groovy
Labels: 2-medium, geneva

#166 Update to use x86 snapcraft image for all snap releases
  src/test/groovy/edgeXReleaseSnapSpec.groovy
  vars/edgeXReleaseSnap.groovy
Labels: bug, enhancement, geneva

#162 create documentation related to manual version bump process
  docs/images/manual-bump-asciicinema.png
  docs/manual-bump.md
Labels: documentation, geneva

#167 Fix bug with EdgeXReleaseGitTag working dir within parallel steps
  src/test/groovy/edgeXReleaseGitTagSpec.groovy
  vars/edgeXReleaseGitTag.groovy
Labels: bug, geneva

#169 Add edgeXSemver bump command to command sequence
  src/test/groovy/edgeXReleaseGitTagSpec.groovy
  vars/edgeXReleaseGitTag.groovy
Labels: bug, geneva

#170 Set semverBumpLevel prefix default to be dev
  src/test/groovy/edgeXReleaseGitTagSpec.groovy
  vars/edgeXReleaseGitTag.groovy
Labels: bug, geneva

#172 ci(groovy): update previous to origin/HEAD
  src/test/groovy/edgexSpec.groovy
  vars/edgex.groovy
Labels: bug, geneva

#173 revert prev logic and add release check
  src/test/groovy/edgexSpec.groovy
  vars/edgex.groovy
Labels: bug, geneva

#176 Set SEMVER_BRANCH to be releaseStream
  src/test/groovy/edgeXReleaseGitTagSpec.groovy
  vars/edgeXReleaseGitTag.groovy
Labels: bug, geneva
