Repository edgexfoundry/edgex-global-pipelines, pull requests merged in 2020-11, with the labels that each got.

#289 refactor: Additional fixes for publishing GitHub pages
  Jenkinsfile
  vars/edgeXGHPagesPublish.groovy
Labels: 1-low, hanoi

#290 docs(jenkins): Add documentation for unit testing prescriptive guidance
  docs_src/tutorials/unit-testing-guidance.md
  mkdocs.yml
Labels: documentation

#291 fix: Commit message in gh-pages branch
  resources/github-pages-publish.sh
  src/test/groovy/edgeXGHPagesPublishSpec.groovy
  vars/edgeXGHPagesPublish.groovy
Labels: 1-low, bug, documentation, hanoi

#265 feat: inline Snyk docker image scan
  src/test/groovy/edgeXBuildCAppSpec.groovy
  src/test/groovy/edgeXBuildDockerSpec.groovy
  src/test/groovy/edgeXBuildGoAppSpec.groovy
  src/test/groovy/edgeXBuildGoParallelSpec.groovy
  src/test/groovy/edgeXSnykSpec.groovy
  vars/edgeXBuildCApp.groovy
  vars/edgeXBuildDocker.groovy
  vars/edgeXBuildGoApp.groovy
  vars/edgeXBuildGoParallel.groovy
  vars/edgeXSnyk.groovy
Labels: wip

#292 fix: launch isolated node for amd64 builds
  vars/edgeXBuildCApp.groovy
  vars/edgeXBuildGoApp.groovy
Labels: 2-medium, bug

#293 ci: remove GOTESTFLAGS
  vars/edgeXBuildGoParallel.groovy
Labels: 2-medium, ci

#294 docs(jenkins): Rename and consolidate unit testing best practices
  docs_src/tutorials/unit-testing-best-practices.md
  docs_src/tutorials/unit-testing-guidance.md
  mkdocs.yml
Labels: documentation

#295 refactor: docker login in all prep stages
  vars/edgeXBuildCApp.groovy
  vars/edgeXBuildDocker.groovy
  vars/edgeXBuildGoApp.groovy
  vars/edgeXBuildGoParallel.groovy
Labels: 2-medium, hanoi

#296 style: update code style and include stashName
  Jenkinsfile
  vars/edgeXGHPagesPublish.groovy
Labels: 1-low, ci

#299 feat: add hanoi to valid release stream
  src/test/groovy/edgexSpec.groovy
  vars/edgex.groovy
Labels: hanoi

#300 bug: fix Snyk C scan image name
  vars/edgeXBuildCApp.groovy
Labels: bug

#287 feat(ci): add verification and force feature of docker images in release flow
  src/test/groovy/edgeXReleaseDockerImageIntSpec.groovy
  vars/edgeXReleaseDockerImage.groovy
Labels: 1-low, ci, hanoi

#303 fix: require check before running edgeXDockerLogin
  vars/edgeXBuildCApp.groovy
  vars/edgeXBuildGoApp.groovy
  vars/edgeXBuildGoParallel.groovy
Labels: 3-high, bug, ireland
