Repository edgexfoundry/edgex-global-pipelines, pull requests merged in 2020-02, with the labels that each got.

#98 Fix bug with Synk and Clair image scanning
  vars/edgeXBuildCApp.groovy
  vars/edgeXBuildDocker.groovy
  vars/edgeXBuildGoApp.groovy
Labels: bug

#99 Disable snyk scans for non-Go pipelines
  vars/edgeXBuildCApp.groovy
  vars/edgeXBuildDocker.groovy
Labels: geneva

#103 fix issue with nexus GIT_COMMIT tagged images
  vars/edgeXBuildDocker.groovy
Labels: bug, geneva

#105 fix clair scan for Go App based images
  vars/edgeXBuildGoApp.groovy
Labels: bug

#107 add auto bump of experimental tag
  Jenkinsfile
Labels: enhancement, geneva

#108 Add ssh-agent to allow authentication of git commands
  Jenkinsfile
Labels: bug

#110 remove lf functions
  Jenkinsfile
Labels: bug

#111 revert experimental tagging
  Jenkinsfile
Labels: bug

#112 add script to auto bump experimental tag
  Jenkinsfile
Labels: geneva

#113 remove -s argument
  scripts/update-named-tag.sh
Labels: bug

#115 add new option for alpine based builds
  test/edgeXBuildGoAppSpec.groovy
  vars/edgeXBuildGoApp.groovy
Labels: enhancement, geneva
