Repository edgexfoundry/edgex-global-pipelines, pull requests merged in 2020-10, with the labels that each got.

#254 docs: update named branch documentation
  docs/manual-bump.md
Labels: 1-low, documentation, hanoi

#253 Update edgeXSemver to resolve semver tag issue
  src/test/groovy/edgeXReleaseGitTagSpec.groovy
  src/test/groovy/edgeXSemverSpec.groovy
  vars/edgeXBuildGoApp.groovy
  vars/edgeXReleaseGitTag.groovy
  vars/edgeXSemver.groovy
Labels: bug, hanoi

#256 feat: add docker support for lfInfraShipLogs
  src/test/groovy/edgeXInfraPublishSpec.groovy
  vars/edgeXInfraPublish.groovy
  vars/edgeXInfraShipLogs.groovy
Labels: 1-low, enhancement, hanoi

#263 feat: documentation generation for edgex-global-pipelines
  .gitignore
  Jenkinsfile
  build.gradle
  docs/index.html
  docs_src/assets/javascripts/version-select.js
  docs_src/assets/logo_edgex.png
  docs_src/assets/logo_edgex_white.png
  docs_src/assets/stylesheets/branding.css
  docs_src/assets/stylesheets/version-select.css
  docs_src/md_files/edgeXBuildCApp.md
  docs_src/md_files/edgeXBuildDocker.md
  docs_src/md_files/edgeXBuildGoApp.md
  docs_src/md_files/header.md
  docs_src/md_files/index.md
  mkdocs.yml
  publish.gradle
  src/main/groovy/edgeXDocGenerator.groovy
  vars/edgeXBuildCApp.groovy
  vars/edgeXBuildDocker.groovy
  vars/edgeXBuildGoApp.groovy
Labels: 2-medium, good first issue, hanoi

#262 feat: add rebuilding artifact as part of edgeXRelease
  src/test/groovy/edgeXReleaseGitTagSpec.groovy
  src/test/groovy/edgeXReleaseGitTagUtilSpec.groovy
  src/test/groovy/edgeXReleaseSpec.groovy
  vars/edgeXRelease.groovy
  vars/edgeXReleaseGitTag.groovy
  vars/edgeXReleaseGitTagUtil.groovy
Labels: 2-medium

#267 fix: publish on isolated node
  Jenkinsfile
Labels: 2-medium, bug

#269 fix: To speed up publish github pages stage
  Jenkinsfile
Labels: 1-low, documentation

#270 docs: update header with WIP
  docs_src/md_files/header.md
Labels: documentation

#272 refactor: remove markdown files in libraries
  Jenkinsfile
  docs_src/libraries/.gitkeep
  docs_src/libraries/edgeXBuildCApp.md
  docs_src/libraries/edgeXBuildDocker.md
  docs_src/libraries/edgeXBuildGoApp.md
Labels: 2-medium, hanoi, tech-debt

#273 fix: permission change for .semver directory
  src/test/groovy/edgeXSemverSpec.groovy
  vars/edgeXSemver.groovy
Labels: 3-high, hanoi

#274 feat: use dockerfile as agent for mkdocs stage
  Jenkinsfile
Labels: 1-low, hanoi

#275 docs(jenkins): Add documentation for using PR commit hash for Jenkins…
  README.md
  docs_src/tutorials/images/draft-pr.png
  docs_src/tutorials/images/find-commit.png
  docs_src/tutorials/index.md
  docs_src/tutorials/pr-commit-for-testing.md
Labels: 1-low, documentation, hanoi

#280 feat(jenkins)remove logic to publish snaps from release execution
  src/test/groovy/edgeXReleaseSpec.groovy
  vars/edgeXRelease.groovy
Labels: 1-low, hanoi

#282 fix: log publishing errors should not fail the builds
  vars/edgeXInfraPublish.groovy
Labels: 2-medium, bug

#276 refactor: Unit tests for edgeXDocGeneration
  .idea/compiler.xml
  .idea/misc.xml
  docs_src/index.md
  src/main/groovy/edgeXDocGenerator.groovy
  src/test/groovy/edgeXDocGeneratorSpec.groovy
Labels: 1-low, ci, hacktoberfest-accepted, hanoi

#286 fix: Unit tests method signatures renamed to be unique
  src/test/groovy/edgexSpec.groovy
Labels: 1-low, ci

#285 Mocking file object for fetchIndexHeader unit test
  src/test/groovy/edgeXDocGeneratorSpec.groovy
Labels: 1-low, ci

#283 feat(jenkins): Shared library for github-pages publish
  .gitignore
  Jenkinsfile
  resources/github-pages-publish.sh
  src/test/groovy/edgeXGHPagesPublishSpec.groovy
  vars/edgeXGHPagesPublish.groovy
Labels: enhancement, hanoi, wip

#288 add link to pr-commit tutorial
  mkdocs.yml
Labels: 1-low, documentation
