Repository edgexfoundry/edgex-global-pipelines, pull requests merged in 2021-06, with the labels that each got.

#337 fix: ensure bump always happens if tag happens.
  vars/edgeXRelease.groovy
Labels: ireland

#338 feat: use latest tag when pushing images
  vars/edgeXBuildGoParallel.groovy
Labels: 2-medium, enhancement

#339 ci: disable snap builds temporary due to upstream Go issue
  mkdocs.yml
  vars/edgeXBuildGoParallel.groovy
Labels: 2-medium, ci

#340 ci: enable snap builds again and fix google analytics tag
  mkdocs.yml
  vars/edgeXBuildGoParallel.groovy
Labels: ci
