Repository edgexfoundry/edgex-global-pipelines, pull requests merged in 2021-03, with the labels that each got.

#321 fix: jobDetails should be defaulted to null
  vars/edgeXEmailUtil.groovy
Labels: bug, ci

#322 docs: update documentation for edgeXBuildGoApp and edgeXBuildGoParallel
  docs_src/libraries/images/edgeXBuildGoApp.png
  docs_src/libraries/images/edgeXBuildGoParallel.png
  vars/edgeXBuildGoApp.groovy
  vars/edgeXBuildGoParallel.groovy
Labels: documentation, ireland

#324 feat: only fail stage artifact stage if possible to build artifact
  src/test/groovy/edgeXReleaseSpec.groovy
  vars/edgeXRelease.groovy
Labels: 1-low, ireland

#325 doc: Update the documentation for the following pre-built pipelines
  docs_src/libraries/images/edgeXBuildCApp.png
  docs_src/libraries/images/edgeXBuildDocker.png
  mkdocs.yml
  vars/edgeXBuildCApp.groovy
  vars/edgeXBuildDocker.groovy
  vars/edgeXBuildGoApp.groovy
  vars/edgeXBuildGoMod.groovy
  vars/edgeXBuildGoParallel.groovy
Labels: documentation, ireland
