Repository edgexfoundry/edgex-global-pipelines, pull requests merged in 2021-02, with the labels that each got.

#317 refactor: Cleaning up edgeXSnyk docker image scan stages from global pipelines
  src/test/groovy/edgeXBuildCAppSpec.groovy
  src/test/groovy/edgeXBuildDockerSpec.groovy
  src/test/groovy/edgeXBuildGoAppSpec.groovy
  src/test/groovy/edgeXBuildGoParallelSpec.groovy
  vars/edgeXBuildCApp.groovy
  vars/edgeXBuildDocker.groovy
  vars/edgeXBuildGoApp.groovy
  vars/edgeXBuildGoParallel.groovy
Labels: ireland

#318 Parallel jobs: get cost data from dynamic nodes
  vars/edgeXBuildGoApp.groovy
  vars/edgeXBuildGoParallel.groovy
  vars/edgeXGeneric.groovy
Labels: 2-medium, ci, enhancement

#316 feat: Add ability to send HTML emails on build failure
  resources/build-log-extract.sh
  resources/email/build-notification-template.html
  src/test/groovy/edgeXBuildCAppSpec.groovy
  src/test/groovy/edgeXBuildDockerSpec.groovy
  src/test/groovy/edgeXBuildGoAppSpec.groovy
  src/test/groovy/edgeXBuildGoParallelSpec.groovy
  src/test/groovy/edgeXEmailSpec.groovy
  src/test/groovy/edgeXEmailUtilSpec.groovy
  vars/edgeXBuildCApp.groovy
  vars/edgeXBuildDocker.groovy
  vars/edgeXBuildGoApp.groovy
  vars/edgeXBuildGoParallel.groovy
  vars/edgeXEmail.groovy
  vars/edgeXEmailUtil.groovy
  vars/edgeXInfraPublish.groovy
Labels: 2-medium, enhancement, ireland, wip

#320 fix: reference to old email method
  vars/edgeXBuildCApp.groovy
  vars/edgeXBuildDocker.groovy
  vars/edgeXBuildGoApp.groovy
  vars/edgeXBuildGoParallel.groovy
Labels: 2-medium, bug
