Repository edgexfoundry/edgex-global-pipelines, pull requests merged in 2021-04, with the labels that each got.

#333 docs: Add badges to readme
  README.md
Labels: documentation

#334 fix: update permission for build artifacts
  src/test/groovy/edgeXBuildGoAppSpec.groovy
  vars/edgeXBuildGoApp.groovy
Labels: bug

#336 feat: make Go 1.16 the default Go version
  src/test/groovy/edgeXBuildGoAppSpec.groovy
  src/test/groovy/edgeXBuildGoParallelSpec.groovy
  src/test/groovy/edgexSpec.groovy
  vars/edgeXBuildGoApp.groovy
  vars/edgeXBuildGoMod.groovy
  vars/edgeXBuildGoParallel.groovy
  vars/edgex.groovy
Labels: enhancement, ireland
