Repository edgexfoundry/edgex-global-pipelines, pull requests merged in 2021-01, with the labels that each got.

#309 bug: publish via curl @file rather than raw cat
  resources/edgex-publish-swagger.sh
Labels: 2-medium, bug, ireland

#311 fix: use --data-binary instead of -d
  resources/edgex-publish-swagger.sh
Labels: 2-medium, ireland

#308 Implement ability to release an EdgeX code repo from a specific commit
  src/test/groovy/edgeXReleaseGitTagSpec.groovy
  src/test/groovy/edgeXReleaseGitTagUtilSpec.groovy
  src/test/groovy/edgeXReleaseSpec.groovy
  vars/edgeXBuildCApp.groovy
  vars/edgeXBuildDocker.groovy
  vars/edgeXBuildGoApp.groovy
  vars/edgeXBuildGoParallel.groovy
  vars/edgeXRelease.groovy
  vars/edgeXReleaseGitTag.groovy
  vars/edgeXReleaseGitTagUtil.groovy
Labels: enhancement, ireland

#314 feat: Go modules bump pre-release version now
  src/test/groovy/edgeXBuildGoModSpec.groovy
  vars/edgeXBuildGoMod.groovy
Labels: 2-medium, enhancement, ireland
