Repository edgexfoundry/edgex-global-pipelines, pull requests merged in 2022-04, with the labels that each got.

#379 feat: new global function for docs releases
  src/test/groovy/edgeXReleaseDocsSpec.groovy
  vars/edgeXRelease.groovy
  vars/edgeXReleaseDocs.groovy
Labels: enhancement, kamakura

#380 docs: Adding new documentation for library functions
  Dockerfile.docs
  Jenkinsfile
  docs_src/index.md
  docs_src/libraries/.gitkeep
  mkdocs.yml
  src/test/groovy/edgeXDockerSpec.groovy
  vars/edgeXClair.groovy
  vars/edgeXCodecov.groovy
  vars/edgeXDocker.groovy
  vars/edgeXDockerLogin.groovy
  vars/edgeXEmail.groovy
  vars/edgeXEmailUtil.groovy
  vars/edgeXGHPagesPublish.groovy
  vars/edgeXGeneric.groovy
Labels: documentation

#382 docs: More new documentation for library functions
  docs_src/index.md
  mkdocs.yml
  vars/edgeXInfraLFToolsSign.groovy
  vars/edgeXInfraPublish.groovy
  vars/edgeXInfraShipLogs.groovy
  vars/edgeXLTS.groovy
  vars/edgeXNexusPublish.groovy
  vars/edgeXReleaseSnap.groovy
  vars/edgeXSetupEnvironment.groovy
  vars/edgeXSnap.groovy
Labels: documentation

#381 feat: use Python-base git-semver capability
  src/test/groovy/edgeXReleaseGitTagSpec.groovy
  src/test/groovy/edgeXReleaseGitTagUtilSpec.groovy
  src/test/groovy/edgeXSemverSpec.groovy
  vars/edgeXBuildGoApp.groovy
  vars/edgeXReleaseGitTag.groovy
  vars/edgeXReleaseGitTagUtil.groovy
  vars/edgeXSemver.groovy
Labels: enhancement

#383 docs: Additional documentation for existing functions
  docs_src/index.md
  mkdocs.yml
  vars/edgeXNexusPublish.groovy
  vars/edgeXRelease.groovy
  vars/edgeXReleaseDockerImage.groovy
  vars/edgeXReleaseDocs.groovy
  vars/edgeXReleaseGitHubAssets.groovy
  vars/edgeXReleaseGitTag.groovy
  vars/edgeXReleaseGitTagUtil.groovy
  vars/edgeXSetupEnvironment.groovy
Labels: ci

#384 feat: add new Golang 1.17 LTS base image
  vars/edgex.groovy
Labels: enhancement
