Repository edgexfoundry/edgex-global-pipelines, pull requests merged in 2022-05, with the labels that each got.

#385 feat: add kamakura as valid release branch
  vars/edgex.groovy
Labels: kamakura

#386 docs: Additional documentation for existing functions
  docs_src/index.md
  mkdocs.yml
  vars/edgeXDocker.groovy
  vars/edgeXEmail.groovy
  vars/edgeXGHPagesPublish.groovy
  vars/edgeXInfraLFToolsSign.groovy
  vars/edgeXInfraPublish.groovy
  vars/edgeXNexusPublish.groovy
  vars/edgeXReleaseDockerImage.groovy
  vars/edgeXReleaseGitHubAssets.groovy
  vars/edgeXSemver.groovy
  vars/edgeXSnyk.groovy
  vars/edgeXSwaggerPublish.groovy
  vars/edgeXUpdateNamedTag.groovy
  vars/edgex.groovy
Labels: documentation

#387 ci: add disableConcurrentBuilds to better handle git-semver issues
  vars/edgeXBuildCApp.groovy
  vars/edgeXBuildGoApp.groovy
  vars/edgeXBuildGoParallel.groovy
Labels: 2-medium, ci

#396 feat: Snyk enhancements for projectName and debug
  src/test/groovy/edgeXBuildGoAppSpec.groovy
  src/test/groovy/edgeXBuildGoParallelSpec.groovy
  src/test/groovy/edgeXSnykSpec.groovy
  vars/edgeXBuildGoApp.groovy
  vars/edgeXBuildGoParallel.groovy
  vars/edgeXSnyk.groovy
Labels: enhancement
